# Generated by Django 5.0.1 on 2024-01-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='siempre',
        ),
    ]
