# Generated by Django 5.0.1 on 2024-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_siempre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('Área', 'Área'), ('CALIDAD', 'CALIDAD'), ('CENTROS MÉDICOS', 'CENTROS MÉDICOS'), ('DOCTORES CENTROS MÉDICOS', 'DOCTORES CENTROS MÉDICOS'), ('ESTERILIZACIÓN', 'ESTERILIZACIÓN'), ('GERENCIA ADMINISTRACIÓN', 'GERENCIA ADMINISTRACIÓN'), ('GERENCIA GENERAL', 'GERENCIA GENERAL'), ('GERENCIA FINANZAS', 'GERENCIA FINANZAS'), ('GERENCIA AMBULATORIA', 'GERENCIA AMBULATORIA'), ('GERENCIA DE SALUD', 'GERENCIA DE SALUD'), ('GERENCIA COMERCIAL', 'GERENCIA COMERCIAL'), ('LABORATORIO', 'LABORATORIO'), ('MATERNIDAD/NEO', 'MATERNIDAD/NEO'), ('PABELLÓN', 'PABELLÓN'), ('UNIDAD DE EXAMENES', 'UNIDAD DE EXAMENES'), ('UNIDAD HOSPITALIZACIÓN', 'UNIDAD HOSPITALIZACIÓN'), ('UTI', 'UTI'), ('URGENCIA/RECEPCIÓN DE URGENCIAS', 'URGENCIA/RECEPCIÓN DE URGENCIAS'), ('OTRAS UNIDADES', 'OTRAS UNIDADES')], default='Área', max_length=100, null=True, verbose_name='Área'),
        ),
    ]
