# Generated by Django 5.0.1 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(max_length=60, verbose_name='Entrada')),
                ('fondo', models.CharField(max_length=60, verbose_name='Fondo')),
                ('postre', models.CharField(max_length=60, verbose_name='Postre')),
                ('hipocal', models.CharField(max_length=60, verbose_name='Hipocalórico')),
            ],
        ),
    ]
