# Generated by Django 5.0.1 on 2024-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='entrada',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fondo',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hipocal',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Hipocalórico'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='postre',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Postre'),
        ),
    ]
